# Input
input: "az://nextflow/raw_data/L0001/*_L001_R{1,2}_001.fastq.gz"
project: 'L0001'
locus_index: 'az://nextflow/reference/transition_panel/locus_indices_latest.csv'
reporting_groups: '4'
baseline: 'az://nextflow/reference/transition_panel/101023_Chin_baseline_noRoSA_4repunits.csv'