# Input
input: "az://nextflow/raw_data/test/*_L001_R{1,2}_001.fastq.gz"
project: 'transition_test'
outdir: 'az://nextflow/results/transition'
locus_index: 'az://nextflow/reference/transition_panel/locus_indices_latest.csv'
reporting_groups: '4'
baseline: 'az://nextflow/reference/transition_panel/101023_Chin_baseline_noRoSA_4repunits.csv'
panel: 'transition'
reference: 
 - 'az://nextflow/reference/transition_panel/transition.fasta'
 - 'az://nextflow/reference/transition_panel/target_fastas/WRAP/WRAP.fasta'
ots28_baseline: 'az://nextflow/reference/full_panel/RoSA_baseline_partial_infile.txt'