# Input
input: "examples/fastqs/*_R{1,2}_concatenated.fastq.gz"
project: 'test_run_with_concat'
outdir: 'test/output'
ots28_missing_threshold: 0.7
pofz_threshold: 0.8
trim_params: "LEADING:15 TRAILING:15 SLIDINGWINDOW:4:15 MINLEN:36"
gsi_missing_threshold: 0.6
max_overlap: 400
loci_to_remove: "(NC_037130\\.1:1062935[.-]1063235)|(NC_037130\\.1:864908[.-]865208)|(NC_037104\\.1:56552952[.-]56553042)"
locus_index: 'data/indices/transition_loci_indices_20241104.csv'
baseline: 'data/baselines/full/SWFSC-chinook-reference-baseline-CV.csv'
panel: 'full'
input_format: "auto"
min_overlap: 3
adapter_file: "data/adapters/GTseq-PE.fa"
ots28_baseline: "data/baselines/full/RoSA_baseline_partial_infile.txt"
n_loci: 204
rubias_show_missing_data: "TRUE"
panel: "full"
concat_all_reads: false
use_sequoia: TRUE
sequoia_mode: "par"
sequoia_missing_threshold: 0.5
parent_geno_input: "examples/PBT/FRH2024_reference_genotypes.txt"
parent_lifehistory: "examples/PBT/FRH2024_reference_lifehistory.txt"
offspring_birthyear: "unknown"
offspring_minBY: "unknown"
offspring_maxBY: 2025
offspring_max_age: 8
species_min_repro_age: 1
species_max_repro_age: 8