# Input
input: "az://nextflow/raw_data/L0001/*_L001_R{1,2}_001.fastq.gz"
project: 'L0001'
outdir: 'az://nextflow/results/fullGT'
locus_index: 'az://nextflow/reference/full_panel/...'
reporting_groups: '4'
baseline: 'az://nextflow/reference/full_panel/...'
panel: 'transition'
reference: 'az://nextflow/reference/full_panel/reference/full_panel/chinook_FullPanel_RosaTransition_March2024.fasta'
baseline_vcf: 'az://nextflow/reference/full_panel/...'